// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnlbvgnnfdewyawnoevm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhubGJ2Z25uZmRld3lhd25vZXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzIwNTcsImV4cCI6MjA2NDIwODA1N30.vWEy91tFO8kd_7C9SMj5PLAclAKHXjg5Nn5xbsMSAA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);